// <auto-generated />
using System;
using IMAS.API.LejarAm.Shared.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMAS.API.LejarAm.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    [Migration("20250824122910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMAS.API.LejarAm.Shared.Domain.Entities.AuditTrailEntities", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuditTrailFilterEntitiesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Butiran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KeteranganAkaun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodAkaun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Kredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NamaPenghutang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TarikhDoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AuditTrailFilterEntitiesID");

                    b.ToTable("AuditTrial");
                });

            modelBuilder.Entity("IMAS.API.LejarAm.Shared.Domain.Entities.AuditTrailFilterEntities", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoAkhir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoMula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDokumen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TahunKewangan")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarikhAkhir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhMula")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AuditTrailFilter");
                });

            modelBuilder.Entity("IMAS.API.LejarAm.Shared.Domain.Entities.JurnalEntities", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisJurnal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoJurnal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoRujukan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SumberTransaksi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TarikhJurnal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Jurnal");
                });

            modelBuilder.Entity("IMAS.API.LejarAm.Shared.Domain.Entities.PenyelenggaraanLejarEntities", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisAkaun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisAkaunParas2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisAliran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisKedudukanPenyata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodAkaun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Paras")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PenyelenggaraanLejar");
                });

            modelBuilder.Entity("IMAS.API.LejarAm.Shared.Domain.Entities.AuditTrailEntities", b =>
                {
                    b.HasOne("IMAS.API.LejarAm.Shared.Domain.Entities.AuditTrailFilterEntities", "AuditTrailFilterEntities")
                        .WithMany("AuditTrails")
                        .HasForeignKey("AuditTrailFilterEntitiesID");

                    b.Navigation("AuditTrailFilterEntities");
                });

            modelBuilder.Entity("IMAS.API.LejarAm.Shared.Domain.Entities.AuditTrailFilterEntities", b =>
                {
                    b.Navigation("AuditTrails");
                });
#pragma warning restore 612, 618
        }
    }
}
