// <auto-generated />
using System;
using IMAS.API.AkaunBelumTerima.Shared.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMAS.API.AkaunBelumTerima.Migrations
{
    [DbContext(typeof(AkaunBelumTerimaDbContext))]
    partial class AkaunBelumTerimaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.BillEntities", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoArahanKerja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoBil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoFixedBil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penyedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PenyelenggaraanPenghutangEntitiesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusJana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TarikhAkhir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TarikhMula")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PenyelenggaraanPenghutangEntitiesID");

                    b.ToTable("BillEntities");
                });

            modelBuilder.Entity("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.NotaDebitKreditEntities", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ButiranNota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoNota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PenyelenggaraanPenghutangEntitiesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusPos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PenyelenggaraanPenghutangEntitiesID");

                    b.ToTable("NotaDebitKreditEntities");
                });

            modelBuilder.Entity("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.PenyelenggaraanPenghutangEntities", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeteranganKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPenghutang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaKedua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoAkaun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TahunKewangan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TarikhJanaan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PenyelenggaraanPenghutangEntities");
                });

            modelBuilder.Entity("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.ResitEntities", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Butiran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoBankSlip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoResit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PenyelenggaraanPenghutangEntitiesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusPos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PenyelenggaraanPenghutangEntitiesID");

                    b.ToTable("ResitEntities");
                });

            modelBuilder.Entity("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.BillEntities", b =>
                {
                    b.HasOne("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.PenyelenggaraanPenghutangEntities", "PenyelenggaraanPenghutangEntities")
                        .WithMany()
                        .HasForeignKey("PenyelenggaraanPenghutangEntitiesID");

                    b.Navigation("PenyelenggaraanPenghutangEntities");
                });

            modelBuilder.Entity("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.NotaDebitKreditEntities", b =>
                {
                    b.HasOne("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.PenyelenggaraanPenghutangEntities", "PenyelenggaraanPenghutangEntities")
                        .WithMany()
                        .HasForeignKey("PenyelenggaraanPenghutangEntitiesID");

                    b.Navigation("PenyelenggaraanPenghutangEntities");
                });

            modelBuilder.Entity("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.ResitEntities", b =>
                {
                    b.HasOne("IMAS.API.AkaunBelumTerima.Shared.Domain.Entities.PenyelenggaraanPenghutangEntities", "PenyelenggaraanPenghutangEntities")
                        .WithMany()
                        .HasForeignKey("PenyelenggaraanPenghutangEntitiesID");

                    b.Navigation("PenyelenggaraanPenghutangEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
